using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WinBioWrapper.Types
{
    public enum WINBIO_BIOMETRIC_SUBTYPE : byte
    {
        WINBIO_SUBTYPE_NO_INFORMATION = 0,
        WINBIO_ANSI_381_POS_UNKNOWN = 0,
        WINBIO_ANSI_381_POS_RH_THUMB = 1,
        WINBIO_ANSI_381_POS_RH_INDEX_FINGER = 2,
        WINBIO_ANSI_381_POS_RH_MIDDLE_FINGER = 3,
        WINBIO_ANSI_381_POS_RH_RING_FINGER = 4,
        WINBIO_ANSI_381_POS_RH_LITTLE_FINGER = 5,
        WINBIO_ANSI_381_POS_LH_THUMB = 6,
        WINBIO_ANSI_381_POS_LH_INDEX_FINGER = 7,
        WINBIO_ANSI_381_POS_LH_MIDDLE_FINGER = 8,
        WINBIO_ANSI_381_POS_LH_RING_FINGER = 9,
        WINBIO_ANSI_381_POS_LH_LITTLE_FINGER = 10,
        WINBIO_ANSI_381_POS_RH_FOUR_FINGERS = 13,
        WINBIO_ANSI_381_POS_LH_FOUR_FINGERS = 14,
        WINBIO_ANSI_381_POS_TWO_THUMBS = 15,
        WINBIO_ANSI_381_POS_UNKNOWN_PALM = 20,
        WINBIO_ANSI_381_POS_RH_FULL_PALM = 21,
        WINBIO_ANSI_381_POS_RH_WRITERS_PALM = 22,
        WINBIO_ANSI_381_POS_LH_FULL_PALM = 23,
        WINBIO_ANSI_381_POS_LH_WRITERS_PALM = 24,
        WINBIO_ANSI_381_POS_RH_LOWER_PALM = 25,
        WINBIO_ANSI_381_POS_RH_UPPER_PALM = 26,
        WINBIO_ANSI_381_POS_LH_LOWER_PALM = 27,
        WINBIO_ANSI_381_POS_LH_UPPER_PALM = 28,
        WINBIO_ANSI_381_POS_RH_OTHER = 29,
        WINBIO_ANSI_381_POS_LH_OTHER = 30,
        WINBIO_ANSI_381_POS_RH_INTERDIGITAL = 31,
        WINBIO_ANSI_381_POS_RH_THENAR = 32,
        WINBIO_ANSI_381_POS_RH_HYPOTHENAR = 33,
        WINBIO_ANSI_381_POS_LH_INTERDIGITAL = 34,
        WINBIO_ANSI_381_POS_LH_THENAR = 35,
        WINBIO_ANSI_381_POS_LH_HYPOTHENAR = 36,
        WINBIO_SUBTYPE_ANY = 0xFF
    }
}
